#!/usr/bin/env bash
# git speed
alias gwd="git diff --no-ext-diff --patch-with-stat"
alias gwdc="gwd --cached"
alias gco="git checkout"
alias gws="git status --short"
alias gc="git commit"
alias gcm="git commit --message"
alias gcam="git commit --verbose --amend"
alias gcf="git commit --amend --reuse-message HEAD"
alias gl="git log --all --graph --oneline --decorate"
alias grot="git rebase origin/trunk"
alias gs="git stash"
alias gsl="git stash list"
alias gss="git stash show"
alias gsa="git stash apply"

# git current branch
alias gbc="git branch | grep \* | cut -d ' ' -f2"
# git branch set upstream
alias gbsu="git branch --set-upstream-to=origin/\$(gbc) \$(gbc)"
# git branch delete interactive
alias gbdi="git branch | fzf -m | xargs git branch -d"
# git branch delete interactive forcefully
alias gbDi="git branch | fzf -m | xargs git branch -D"
# git checkout branch interactive
alias gcoi="git branch | fzf -m | xargs git checkout"

# tmux
alias tn="tmux new -s ' '"
alias tns="tmux new -s"
alias tls="tmux ls"
alias ta="tmux a"
alias tks="tmux kill-session -t"

# misc
alias rg="rg --smart-case"
alias cls="clear; ls"
alias exs="source ~/.zshrc"
alias pyserv="python3 -m http.server"
alias psg="ps aux | head -n 1; ps aux | rg"
alias fix="git diff --name-only | uniq | xargs $EDITOR"
alias cmv="gcm \"\`node -e \"console.log(require('./package.json').version)\"\`\""
alias brewu="brew update; brew upgrade --force-bottle; brew cleanup --prune-prefix; brew doctor"
alias dns="sudo killall -hUP mDNSResponder"