cask_args appdir: "/Applications"

tap "homebrew/core"
tap "homebrew/bundle"
tap "beeftornado/rmtree"

tap "caskroom/cask"
tap "caskroom/fonts"

tap "neovim/neovim"

brew "awscli"
brew "coreutils"
brew "elixir"
brew "fzf"
brew "git"
brew "gnupg"
brew "htop"
brew "imagemagick"
brew "neovim"
brew "python3"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "tmux"
brew "wget"
brew "yarn"
brew "zplug"
brew "zsh"

cask "1password"
cask "alfred"
cask "bartender"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-sourcecodepro-nerd-font-mono"
cask "google-chrome"
cask "gpgtools"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "keka"
cask "ngrok"
cask "slack"
cask "spotify"
cask "transmission"
cask "vlc"
cask "vyprvpn"
