tap "caskroom/fonts"

tap "beeftornado/rmtree"
tap "railwaycat/emacsmacport"

brew "awscli"
brew "coreutils"
brew "elixir"
brew "fzf"
brew "git"
brew "gnupg"
brew "htop"
brew "imagemagick"
brew "neovim"
brew "nvm"
brew "python3"
brew "emacs-mac", args: ["with-gnutls", "with-imagemagick", "with-natural-title-bar", "with-spacemacs-icon", "with-xml2"]
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "tmux"
brew "wget"
brew "yarn"
brew "zplug"
brew "zsh", args: ["without-etcdir"]


cask "1password"
cask "alfred"
cask "bartender"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-sourcecodepro-nerd-font-mono"
cask "google-chrome"
cask "gpgtools"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "keka"
cask "ngrok"
cask "slack"
cask "spotify"
cask "transmission"
cask "vlc"
cask "vyprvpn"
